THESE_WILL_BE_IMPORTED: "to the config file to be used as variables"
STORE: "sensitive data in this file"
#######################################################################
ZM_API:
ZM_PORTAL:
ZM_USER:
ZM_PASS:
ZM_SSL: yes

GOTI_HOST:
GOTI_PORTAL:
GOTI_TOKEN:

PUSHOVER_TOKEN:
PUSHOVER_KEY:

LINKURL_USER:
LINKURL_PASS:
